import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import MyPdfViewer from '../components/MyPdfViwer'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PDF Viewer powere by ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          PDF Viewer powered
          <br />
          by <Link href="https://chat.openai.com/chat">ChatGPT</Link>
        </h1>

        <div className={styles.description}>
          <MyPdfViewer
            file="slides/組織の生産性を高める意思決定の構造と方法.pdf"
          />
        </div>
      </main>
    </div>
  )
}
